language: c
services: docker
os: linux
dist: xenial
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - source xs-opam-ci.env
  - cp  mocks/mock.ml lib/nvml.ml
  - cp  mocks/mock.c  stubs/nvml_stubs.c
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=gpumon
    - PINS="gpumon:."
