name: Build and test

on:
  push:
  pull_request:

jobs:
  ocaml-test:
    name: Ocaml tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v1

      - name: Update Ubuntu repositories
        shell: bash
        run: sudo apt-get update

      - name: Use ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repositories: |
            xs-opam: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true
        env:
          DUNE_CACHE_STORAGE_MODE: copy

      - name: Install dependencies
        shell: bash
        run: opam install . --deps-only --with-test -v

      - name: Build
        shell: bash
        run: |
          opam exec -- cp mocks/mock.ml lib/nvml.ml
          opam exec -- cp mocks/mock.c stubs/nvml_stubs.c
          opam exec -- make

      - name: Run tests
        shell: bash
        run: opam exec -- make test
